#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Build the site
npm run build

# navigate into the build output directory & Add a cname file
# to ensure Github picks up and sets it to the right domain on deploy
cd dist
echo 'danielturcich.com' > CNAME

# add any changed files from the build
git add -A