#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run ESLint and Prettier on all files to ensure no bad commits
pnpm lint-fix
pnpm format-check
# add any changed files from lint-fix
git add -A

# Build the site 
# pnpm run build 

# navigate into the build output directory & Add a cname file
# to ensure Github picks up and sets it to the right domain on deploy
# cd dist
# echo 'danielturcich.com' > CNAME
