# name: Push Action
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Clones repo"
#       - name: Check out repository code
#         uses: actions/checkout@v2

#       - run: echo "Running script"
#       - name: Run script file
#         run: |
#           chmod +x ./deploy.sh
#           ./deploy.sh
#         shell: bash

# This script deploys your website automatically
name: CI

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [master]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
      - uses: actions/checkout@v2

      # Run our deployment command
      - name: Deploying the static website to gh-pages
        run: npm run deploy
